// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gin-template/controller"
	"gin-template/repository"
	"gin-template/router"
	"gin-template/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeAllController(db *gorm.DB) (*router.APIControllers, error) {
	referralRepository := repository.NewReferralRepository(db)
	tokenRepository := repository.NewTokenRepository(db)
	tokenService := service.NewTokenService(tokenRepository)
	referralService := service.NewReferralService(referralRepository, tokenService)
	referralController := controller.NewReferralController(referralService)
	projectRepository := repository.NewProjectRepository(db)
	projectService := service.NewProjectService(projectRepository)
	projectController := controller.NewProjectController(projectService)
	tokenReconciliationRepository := repository.NewTokenReconciliationRepository(db)
	outlineRepository := repository.NewOutlineRepository(db)
	outlineService := service.NewOutlineService(tokenRepository, tokenReconciliationRepository, outlineRepository)
	outlineController := controller.NewOutlineController(outlineService)
	packageRepository := repository.NewPackageRepository(db)
	packageService := service.NewPackageService(packageRepository, tokenService)
	packageController := controller.NewPackageController(packageService)
	apiControllers := &router.APIControllers{
		ReferralController: referralController,
		ProjectController:  projectController,
		OutlineController:  outlineController,
		PackageController:  packageController,
	}
	return apiControllers, nil
}

// wire.go:

// ServiceSet 大纲服务集合
var ServiceSet = wire.NewSet(service.NewOutlineService, service.NewTokenService, service.NewProjectService, service.NewReferralService, service.NewPackageService)

// repository.RepositorySet 基础仓库集合
var RepositorySet = wire.NewSet(repository.NewTokenRepository, repository.NewTokenReconciliationRepository, repository.NewOutlineRepository, repository.NewProjectRepository, repository.NewReferralRepository, repository.NewPackageRepository)

// 控制器依赖注入集合
var ControllerSet = wire.NewSet(controller.NewReferralController, controller.NewProjectController, controller.NewOutlineController, controller.NewPackageController, controller.NewReconciliationController)
